run:
  skip-dirs:
    - example/ # Just example with stubs and unused vars

linters-settings:
  funlen:
    lines: 150
    statements: 100

linters:
  enable-all: true
  disable:
    - ireturn # The abstracted logger exposes only interface functions
    - maligned
